language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    - build@whiteout.io
before_install:
  - "sudo iptables -D INPUT -m tcp --dport 25 -j REJECT"
  - "sudo iptables -D OUTPUT -m tcp --dport 25 -j REJECT"
  - "sudo iptables -D INPUT -m tcp --dport 465 -j REJECT"
  - "sudo iptables -D OUTPUT -m tcp --dport 465 -j REJECT"